config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'

  scope module: :public do
  get 'customers/my_page', to: 'customers#show'
  get 'customers/edit', to: 'customers#edit'
  patch 'customers/withdraw', to: 'customers#withdraw'
  resources :customers, only: [:update]
  get 'customers/quit', to: 'customers#quit'

  resources :addresses

  resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end


  get 'orders/thanks', to: 'orders#thanks'

  resources :orders, only: [:new, :index, :show, :create] do
    collection do
      post :info
    end
  end

 end

  devise_for :customers, controllers: {
    sessions: 'public/customers/sessions',
    passwords: 'public/customers/passwords',
    registrations: 'public/customers/registrations'
  }


  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }



  get '/about' => 'public/homes#about'
  get '/items' => 'public/items#index'
  get '/items/:id', to: 'public/items#show', as: 'item'



  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :products, only: [:edit, :index, :new, :show, :create, :update]
    resources :customers, only: [:index, :edit, :show, :update]
    resources :orders, only: [:show]
    get '/' => 'homes#top'

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active, :id)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_cart_item, only: [:add_item, :destroy]



  def show
    @customer = current_customer
  end

  def destroy
    @customer.destroy
    redirect_to curent_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    @customer.update(customer_params)
    redirect_to customers_my_page_path
  end

  def quit
    @customer = current_customer
  end

  def withdraw
    @customer = current_customer
    @customer.update(is_active: false)
    reset_session
    redirect_to root_path
  end


  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <h4 class="bg-light"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h4>
  </div>
  <div class="row">
    <table>
      <tr>
        <th>会員ID</th><td><%= @customer.id %></td>
      </tr>
      <%= form_with model: @customer, url: admin_customer_path, local:true do |f| %>
      <tr>
        <th><%= f.label :name, "氏名" %></th>
        <td>  <%= f.text_field :last_name, autofocus: true %> <%= f.text_field :first_name, autofocus: true %></td>
      </tr>
      <tr>
        <th><%= f.label :name_kana, "フリガナ" %></th>
        <td><%= f.text_field :last_name_kana, autofocus: true %> <%= f.text_field :first_name_kana, autofocus: true %></td>
      </tr>
      <tr>
        <th><%= f.label :postal_code, "郵便番号" %></th>
        <td><%= f.text_field :postal_code, autofocus: true %></td>
      </tr>
      <tr>
        <th><%= f.label :address, "住所" %></th>
        <td>  <%= f.text_field :address, autofocus: true %></td>
      </tr>
      <tr>
        <th><%= f.label :telephone_number, "電話番号" %></th>
        <td><%= f.text_field :telephone_number, autofocus: true %></td>
      </tr>
      <tr>
        <th><%= f.label :email, "メールアドレス" %></th>
        <td><%= f.text_field :email, autofocus: true %></td>
      </tr>
      <tr>
        <th>会員ステータス</th>
        <td>
          <%= f.radio_button :is_active, "true" %>
          <%= f.label :is_active, "有効" %>
          <%= f.radio_button :is_active, "false" %>
          <%= f.label :is_active, "退会" %>
    　　</td>
      </tr>
      <tr>
        <th></th>
        <td>
          <%= f.hidden_field :id %>
          <%= f.submit "編集内容を保存", class: "btn btn-sm btn-success" %>
        </td>
      </tr>
    </table>
    <% end %>
  </div>
</div>

app/views/admin/customers/edti.html.erb
<div class="container">
  <div class="row">
    <h4 class="bg-light"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h4>
  </div>
  <div class="row">
    <table>
      <tr>
        <th>会員ID</th><td><%= @customer.id %></td>
      </tr>
      <%= form_with model: @customer, url: customer_session_path, local:true do |f| %>
      <tr>
        <th><%= f.label :name, "氏名" %></th>
        <td>  <%= f.text_field :last_name, autofocus: true %> <%= f.text_field :first_name, autofocus: true %></td>
      </tr>
      <tr>
        <th><%= f.label :name_kana, "フリガナ" %></th>
        <td><%= f.text_field :last_name_kana, autofocus: true %> <%= f.text_field :first_name_kana, autofocus: true %></td>
      </tr>
      <tr>
        <th><%= f.label :postal_code, "郵便番号" %></th>
        <td><%= f.text_field :postal_code, autofocus: true %></td>
      </tr>
      <tr>
        <th><%= f.label :address, "住所" %></th>
        <td>  <%= f.text_field :address, autofocus: true %></td>
      </tr>
      <tr>
        <th><%= f.label :telephone_number, "電話番号" %></th>
        <td><%= f.text_field :telephone_number, autofocus: true %></td>
      </tr>
      <tr>
        <th><%= f.label :email, "メールアドレス" %></th>
        <td><%= f.text_field :email, autofocus: true %></td>
      </tr>
      <tr>
        <th>会員ステータス</th>
        <td>
          <%= f.radio_button :is_active, "true" %>
          <%= f.label :is_active, "有効" %>
          <%= f.radio_button :is_active, "false" %>
          <%= f.label :is_active, "無効" %>
    　　</td>
      </tr>
    </table>
    <div class="col text-center">
      <%= f.submit "編集内容を保存", class: "btn btn-sm btn-success" %>
    </div>
    <% end %>
  </div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <h4 class="bg-light">会員一覧</h4>
    <table class="table table-bordered">
      <thead class="bg-light">
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to admin_customer_path(customer.id) do %>
              <%= customer.last_name %> <%= customer.first_name %>
            <% end %>
          </td>
          <td><%= customer.email %></td>
          <% if customer.is_active %>
          <td>有効</td>
          <% else %>
          <td>退会済</td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <h4 class="bg-light"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h4>
  <div class="row">
      <table>
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= @customer.last_name %><%= @customer.first_name %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <% if @customer.is_active %>
          <td>有効</td>
          <% else %>
          <td>退会済</td>
          <% end %>
        </tr>
        <tr>
          <th></th>
          <td>
            <%= link_to '編集する', edit_admin_customer_path(@customer.id), class: "btn btn-success" %>
            <%= link_to '注文履歴を見る', admin_order_path(@customer.id), class: "btn btn-primary" %>
          </td>
        </tr>
      </table>
  </div>
</div>




<p></p>

<div>
  <table>

  </table>
</div>