config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'

  scope module: :public do
  get 'customers/my_page', to: 'customers#show'
  get 'customers/edit', to: 'customers#edit'
  patch 'customers/withdraw', to: 'customers#withdraw'
  resources :customers, only: [:update]
  get 'customers/quit', to: 'customers#quit'

  resources :addresses

  resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end


  get 'orders/thanks', to: 'orders#thanks'

  resources :orders, only: [:new, :index, :show, :create] do
    collection do
      post :info
    end
  end

 end

  devise_for :customers, controllers: {
    sessions: 'public/customers/sessions',
    passwords: 'public/customers/passwords',
    registrations: 'public/customers/registrations'
  }


  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }



  get '/about' => 'public/homes#about'
  get '/items' => 'public/items#index'
  get '/items/:id', to: 'public/items#show', as: 'item'



  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :products, only: [:edit, :index, :new, :show, :create, :update]
    resources :customers, only: [:index, :edit, :show, :update]
    resources :orders, only: [:show]
    get '/' => 'homes#top'

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }


  def add_tax_price
    (price*1.1).floor
  end

  def subtotal_price
    product.add_tax_price*amount
  end

  def total_price
    total_price = 0
    self.order_details.each do |order_detail|
      total_price += order_detail.subtotal_price
    end
    total_price += 800
    return total_price
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @total_price = 0
    @order_details.each do |order_detail|
      @total_price += order_detail.subtotal_price
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @order = Order.new
  end

  def info
    @cart_items = CartItem.all
    @customer = current_customer
    @total_price = 0
    @cart_items.each do |cart_item|
      @total_price += cart_item.subtotal_price
    end
    @order = Order.new(order_params)
    if params[:order][:select_address] == "0"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name =  current_customer.last_name + current_customer.first_name
    elsif params[:order][:select_address] == "1"
      @address = Address.find(params[:order][:chose_address])
      @order.postal_code = @address.postal_code
      @order.address = @address.address
      @order.name = @address.name
    else params[:order][:select_address] == "2"
    end
  end

  def thanks
  end

  def create
    @order = Order.new(order_params)
    @cart_items = CartItem.all
    @order.save
    @cart_items.each do |cart_item|
      @order_details = OrderDetail.new
      @order_details.order_id = @order.id
      @order_details.product_id = cart_item.product_id
      @order_details.price = cart_item.product.price
      @order_details.amount = cart_item.amount
    @order_details.save
    end
    @cart_items.destroy_all
    redirect_to orders_thanks_path
  end

  def index
    @orders = Order.all
    @customer = current_customer
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @total_price = 0
    @order_details.each do |order_detail|
      @total_price += order_detail.subtotal_price
    end
  end

  private

  def order_params
    params.require(:order).permit(:payment_method, :postal_code, :address, :name, :total_payment)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <h4>注文履歴詳細</h4>
  </div>
  <div class="row">
      <table>
        <tr>
           <th>購入者</th>
           <td>
             <%= link_to admin_customer_path(@order.customer_id) do %>
               <%= @order.customer.last_name %> <%= @order.customer.first_name %>
             <% end %>
           </td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th>配達先</th>
          <td>
            <%= @order.postal_code %></br>
            <%= @order.address %></br>
            <%= @order.name %>
          </td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
      </table>
  </div>

  <div class="row">
    <div class="col-7">
      <table class="table table-bordered">
        <thead class="bg-light">
          <tr>
            <th>商品</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.product.name %></td>
            <td><%= order_detail.product.add_tax_price %></td>
            <td><%= order_detail.amount %></td>
            <td><%= order_detail.subtotal_price %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-5">
      <table>
        <tr>
          <th>商品合計</th>
          <td><%= @total_price %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td>800円</td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td><%= @total_price + 800 %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>