config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'

  scope module: :public do
  get 'customers/my_page', to: 'customers#show'
  get 'customers/edit', to: 'customers#edit'
  patch 'customers/withdraw', to: 'customers#withdraw'
  resources :customers, only: [:update]
  get 'customers/quit', to: 'customers#quit'

  resources :addresses

  resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end


  get 'orders/thanks', to: 'orders#thanks'

  resources :orders, only: [:new, :index, :show, :create] do
    collection do
      post :info
    end
  end

 end

  devise_for :customers, controllers: {
    sessions: 'public/customers/sessions',
    passwords: 'public/customers/passwords',
    registrations: 'public/customers/registrations'
  }


  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }



  get '/about' => 'public/homes#about'
  get '/items' => 'public/items#index'
  get '/items/:id', to: 'public/items#show', as: 'item'



  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :products, only: [:edit, :index, :new, :show, :create, :update]
    resources :customers, only: [:index, :edit, :show, :update]
    resources :orders, only: [:show]
    get '/' => 'homes#top'

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer
end

def full_address
  '〒'+ postal_code + ' ' + address + ' ' + name
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :product

  def add_tax_price
    (price*1.1).floor
  end

  def subtotal_price
    product.add_tax_price*amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }


  def add_tax_price
    (price*1.1).floor
  end

  def subtotal_price
    product.add_tax_price*amount
  end

  def total_price
    total_price = 0
    self.order_details.each do |order_detail|
      total_price += order_detail.subtotal_price
    end
    total_price += 800
    return total_price
  end
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product

  def subtotal_price
    product.add_tax_price*amount
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  attachment :image
  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def add_tax_price
    (price*1.1).floor
  end

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
    @address = Address.new
    @addresses = Address.all
  end

  def edit
    @address = Address.find(params[:id])
  end

  def create
    @address = Address.new(address_params)
    @address.save
    redirect_to addresses_path
  end

  def update
    @address = Address.find(params[:id])
    @address.update(address_params)
    redirect_to addresses_path
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to addresses_path
  end

  def address_params
    params.require(:address).permit(:postal_code, :address, :name)
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    @genres = Genre.all
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product.id)
    else
      render action: :new
    end

  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
    @genres = Genre.all
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to admin_product_path(@product.id)
  end

  private

  def product_params
    params.require(:product).permit(:image, :name, :introduction, :genre_id, :price)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_cart_item, only: [:add_item, :destroy]



  def show
    @customer = current_customer
  end

  def destroy
    @customer.destroy
    redirect_to curent_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    @customer.update(customer_params)
    redirect_to customers_my_page_path
  end

  def quit
    @customer = current_customer
  end

  def withdraw
    @customer = current_customer
    @customer.update(is_active: false)
    reset_session
    redirect_to root_path
  end


  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @products = Product.order(created_at: :desc).limit(4)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @products = Product.all.page(params[:page]).per(8)
  end

  def show
    @product = Product.find(params[:id])
    @cart_item = CartItem.new
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @order = Order.new
  end

  def info
    @cart_items = CartItem.all
    @customer = current_customer
    @total_price = 0
    @cart_items.each do |cart_item|
      @total_price += cart_item.subtotal_price
    end
    @order = Order.new(order_params)
    if params[:order][:select_address] == "0"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name =  current_customer.last_name + current_customer.first_name
    elsif params[:order][:select_address] == "1"
      @address = Address.find(params[:order][:chose_address])
      @order.postal_code = @address.postal_code
      @order.address = @address.address
      @order.name = @address.name
    else params[:order][:select_address] == "2"
    end
  end

  def thanks
  end

  def create
    @order = Order.new(order_params)
    @cart_items = CartItem.all
    @order.save
    @cart_items.each do |cart_item|
      @order_details = OrderDetail.new
      @order_details.order_id = @order.id
      @order_details.product_id = cart_item.product_id
      @order_details.price = cart_item.product.price
      @order_details.amount = cart_item.amount
    @order_details.save
    end
    @cart_items.destroy_all
    redirect_to orders_thanks_path
  end

  def index
    @orders = Order.all
    @customer = current_customer
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @total_price = 0
    @order_details.each do |order_detail|
      @total_price += order_detail.subtotal_price
    end
  end

  private

  def order_params
    params.require(:order).permit(:payment_method, :postal_code, :address, :name, :total_payment)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/products/edit.html.erb
<div class="container">
  <h4 class-"bg-light">商品編集</h4>
  <div class="row">
    <%= form_with model: @product, url: admin_product_path, local:true do |f| %>
    <table>
      <tr>
        <th><%= f.label :image, "商品画像" %></th>
        <td><%= f.attachment_field :image %></td>
      </tr>
      <tr>
        <th><%= f.label :name, "商品名" %></th>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <th><%= f.label :introduction, "商品説明" %></th>
        <td><%= f.text_area :introduction %></td>
      </tr>
      <tr>
        <th><%= f.label :genre, "ジャンル" %></th>
        <td><%= f.collection_select(:genre_id, @genres, :id, :name) %></td>
      </tr>
      <tr>
        <th><%= f.label :price, "税抜価格" %></th>
        <td><%= f.text_field :price %>円</div></td>
      </tr>
    </table>
    <%= f.submit "変更を保存", class:"btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="container">
  <div class="row">
    <h4 class="bg-light">商品一覧</h4>
    <div class="col align-right">
      <%= link_to '+', new_admin_product_path, class: "btn btn-secondary rounded-circle" %>
    </div>

    <table class="table table-bordered">
      <thead class="bg-light">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |products| %>
        <tr>
          <td><%= products.id %></td>
          <td><%= link_to products.name, admin_product_path(products) %></td>
          <td><%= products.price %></td>
          <td><%= products.genre.name %></td>
        </tr>
         <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="container">
  <h4 class-"bg-light">新規商品登録</h4>
  <% if @product.errors.any? %>
  　<%= @product.errors.count %>件のエラーが発生しました
  　<% @product.errors.full_messages.each do |message| %>
    　<%= message %>
  　<% end %>
　<% end %>
  <div class="row">
    <%= form_with model: @product, url: admin_products_path, local:true do |f| %>
    <table>
      <tr>
        <th><%= f.label :image, "商品画像" %></th>
        <td><%= f.attachment_field :image %></td>
      </tr>
      <tr>
        <th><%= f.label :name, "商品名" %></th>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <th><%= f.label :introduction, "商品説明" %></th>
        <td><%= f.text_area :introduction %></td>
      </tr>
      <tr>
        <th><%= f.label :genre, "ジャンル" %></th>
        <td><%= f.collection_select(:genre_id, @genres, :id, :name) %></td>
      </tr>
      <tr>
        <th><%= f.label :price, "税抜価格" %></th>
        <td><%= f.text_field :price %>円</div></td>
      </tr>
      <tr>
        <th></th>
        <td><%= f.submit "新規登録", class:"btn btn-success" %></td>
      </tr>
    </table>
    <% end %>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="container">
  <h4 class="bg-light">商品詳細</h4>
  <div class="row">
    <dvi class="col-5">
      <%= attachment_image_tag @product, :image, :fill, 300, 200  %>
    </dvi>
    <div class="col-7">
      <table>
        <tr>
          <th>商品名</th>
          <td><%= @product.name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= @product.introduction %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= @product.genre.name %></td>
        </tr>
        <tr>
          <th>税込価格</br>(税抜価格)</th>
          <td><%= @product.add_tax_price.to_s(:delimited) %>(<%= @product.price %>)</td>
        </tr>
      </table>
      <%= link_to '編集する', edit_admin_product_path(@product), class: "btn btn-success" %>
    </div>
  </div>
</div>